# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-25 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Children',
            new_name='Child',
        ),
    ]
