# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-31 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20191030_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderlineitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderlineitem', to='checkout.OrderLineItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.Order'),
        ),
    ]
