# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20191101_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderlineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderlineitem', to='checkout.OrderLineItem'),
        ),
    ]
