# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-04 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_order_orderlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderlineitem',
        ),
    ]
